# Generated by Django 5.0.6 on 2024-07-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chatmessage_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
