# Generated by Django 5.1.2 on 2024-11-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_post_photo_remove_post_video_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('R', 'In a relationship'), ('C', 'Complicated'), ('M', 'Married')], max_length=1),
        ),
    ]
